//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int PetID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Service Service { get; set; }
    }
}
